TUDelft-CNS-ATM/bluesky

- bluesky/stack/synthetic.py
It doesn't really do something: scr.zoom(1,false), the line was commented out since the call was also done incorrectly and crashed the synthetics module in pygame.
> fixed synthetic.py scr.zoom call

- bluesky/tools/geo.py
In equation for cavelat, "lata + latb.T" was changed to "latb + lata.T", such that it is possible to also have nonsquare matrices as inputs for kwikqdrdist_matrix. The result for kwikqdrdist_matrix with square matrices as inputs is not affected by this change.
> Update geo.py kwikqdrdist_matrix for nonsquare matrices

- bluesky/core/plugin.py
Path.rglob  that was used previously to discover plugins had a bug (https://bugs.python.org/issue33428) that it does not follow symlinks.
So, if in "/plugins/" directory I create a symlink to another directory where I have plugin files, then Path.rglob would just ignore this directory.
I only tested the fix in Linux, I think it should work fine on Mac/Win, but I don't have an opportunity to check that.
> Path.rglob does not follow symlinks

- bluesky/traffic/route.py
ADDWPTMODE command is an alternative to writing
ADDWPT acid FLYTURN => ADDWPTMODE acid FLYTURN
ADDWPT acid TURNSPEED 10 => ADDWPTMODE acid TURNSPEED 10
On top of that, simply entering
ADDWPTMODE acid
echos what mode the addwpt command is in.
> Added implementation of ADDWPTMODE.

- bluesky/traffic/asas/resolution.py
Currently, settings from a previous simulation are preserved after calling reset. Furthermore, self.resopairs still contains resolution pairs from the last timestep before reset. Although this set is updated the first time self.resumenav (function) is executed, problems can occur when referring to self.resopairs before ASAS is updated. This could be fixed by implementing a reset function in the ConflictResolution() class.
> Implement reset function in ConflictResolution() class

- bluesky/ui/console/consoleui.py
- bluesky/ui/qtgl/aman.py
- bluesky/ui/qtgl/console.py
- bluesky/ui/qtgl/customevents.py
- bluesky/ui/qtgl/docwindow.py
- bluesky/ui/qtgl/glhelpers.py
- bluesky/ui/qtgl/gui.py
- bluesky/ui/qtgl/guiclient.py
- bluesky/ui/qtgl/infowindow.py
- bluesky/ui/qtgl/mainwindow.py
- bluesky/ui/qtgl/nd.py
- bluesky/ui/qtgl/radarwidget.py
- bluesky/ui/qtgl/settingswindow.py
- bluesky/ui/qtgl/tiledtexture.py
- extra/blipdriver/blipdriver.py
- extra/blipdriver/glhelpers.py
- extra/textclient/textclient.py
- utils/gltest.py
I added the pyqt5 import statements as a ```try``` and ```except```.
It still doesn't run with pyqt5 though as there are somethings needed to change in ```glhelpers.py``` so that it is compatible with both.
It also seems like pyqt5 may work with enums so we may not have to change those.
---------
I also realized that I made some changes to ```consoleui.py``` but that was me just trying to learn textual. I can take it out of this pull request if you prefer
> Add pyqt5 import statements

- bluesky/ui/console/consoleui.py
The hot keys now work and show the batch view. Needs some work so that they turn each other on/off... at the moment, In order to see the batch you need to first turn traffic off.
Regarding the batch view, I am not sure how to make a progress bar with rich. In my first implementation, I just put a ```with``` statement around the server. It appears that it needs a context manager ([progress in rich](https://rich.readthedocs.io/en/stable/progress.html)). I guess I could do the same around the console client but it doesn't seem elegant ahah.
> mount batch table

- bluesky/ui/loadvisuals_txt.py
- bluesky/ui/qtgl/glhelpers.py
- bluesky/ui/qtgl/gui.py
Both `pyqt5` and `pyqt6` work now..
However there is still something I am not sure about in the `UniformBufferObject` class ([line 946](https://github.com/amorfinv/bluesky/blob/e0b5d85e4392a47a4ee0b9e4606b313dbd7b668d/bluesky/ui/qtgl/glhelpers.py#L946)).
I get this message when closing bluesky (both `pyqt5` and `pyqt6`) if I use `super().__init__(QOpenGLBuffer.Type.VertexBuffer)` in the constructor
```
Qt gui warning: QOpenGLVertexArrayObject::destroy() failed to restore current context
```
If I use `super().__init__(gl.GL_UNIFORM_BUFFER)` instead, then only the `pyqt5` version works.
> working pyqt5 and pyqt6

- bluesky/ui/qtgl/glhelpers.py
It is currently not possible to have pyqt5 and pyqt6 in the same environment. This fix now ensures that correct opengl profiles are loaded.
> make pyqt5 and pyqt6 compatible in same environment

- bluesky/ui/qtgl/tiledtexture.py
I noticed that the tiledmap doesn't work for pyqt5.
Now it does.
-Andres
> patch tiledmap for qt5

- plugins/geofence.py
Hello,
I have brought in the updated geofence plugin. This is similar to the one in the M2 fork but now it is generalized.
I am not sure if it belongs in the main bluesky code because it does require ```shapely``` and ```rtree```.
One of the stack commands, ```loadgeojson``` requires ```geopandas```. The reason is because ```geojson``` data is easy to create with any GIS tool.
If we don't want to add it to the master bluesky I can put it in my ```icrat2022``` [branch](https://github.com/amorfinv/bluesky/tree/icrat2022).
-Andres
> Patch geofence plugin

- bluesky/simulation/screenio.py
- bluesky/ui/qtgl/gltraffic.py
The ```casmach_thr``` value is currently ignored in the gui when it appears on the route constraints
With this fix, the correct speed constraint appears in the waypoint.
> Fix casmach threshold in route(gui)

- bluesky/settings.py
Fixing #404 .
In latest ```settings.py``` bluesky would only create a ```settings.cfg``` file if it was downloaded as a package. This meant that anyone that used ```git clone``` would not be able to create a ```settings.cfg```.
I tested on mac mini so unsure about others.
-Andres
> create config when it does not exist

- bluesky/settings.py
Per #404 BlueSky currently does not populate some directories if using source. Now it should check if they exist and create if necessary.
I am not sure if this is where the code should go where it is or if there should be a function. Since it is not so many lines I guess it can go where it is.
-Andres
> populate directories when they do not exist

- bluesky/ui/qtgl/mainwindow.py
Fix bug in ```QFileDialog.getOpenFileName``` introduced in commit 8a3c5e36 which was reported by @DRKWang in #405 .
The issue arose from trying to resolve conflicting keyword and positional arguments. In the ```pyqt``` [documentation](https://www.riverbankcomputing.com/static/Docs/PyQt5/api/qtwidgets/qfiledialog.html?highlight=qfiledialog#QFileDialog) the fourth argument is reserved for ```filter```. Meanwhile, in the code there are four positional arguments so ```filter``` is set to ```'Scenario files (*.scn)'```. This clashes with the keyword argument ```filter='*.scn'```. I am not sure what the intention is but there is another filter argument called ```initialFilter``` so I just changed it to be ```initialFilter='*.scn'```. The ```pyqt``` documentation is a bit lacking so it is not …
> fix positional arguments in qtfiledialog

- bluesky/tools/aero.py
bluesky.core.aero.vmach2tas it was written "True airspeed (tas) to mach number conversion for numpy arrays" where as the function was converting "Mach number to TAS"
bluesky.core.aero.vtas2eas "A typo of equivent to equivalent"
> Typos correction

- bluesky/traffic/traffic.py
Fixed a bug about the calculation of turnrate, where the original code did not match the calculation formula, resulting in an incorrect calculation of turn rate.
> Update traffic.py: Fix the calculation of turnrate

- bluesky/stack/simstack.py
The scenario file parser would consider a line is empty (or too short to be a command) if its length was shorter than 12. An example of a valid command that would be skipped in this situation is 00:00:01>FF , which has a length of 11.
As the length of the timestamp needs to be at least 9 (including the > symbol), the parser should check whether the length of a line is smaller than 10.
> Fix for short commands being sometimes skipped.

- bluesky/stack/cmdparser.py
https://github.com/TUDelft-CNS-ATM/bluesky/commit/dbaf8ad9c4f9ac18de54bb6edd0b1e46b5aca503 breaks compatibility for Python <3.9 by using annotation features only available in [PEP 593](https://peps.python.org/pep-0593/).
Sadly, the aforementioned commit is already included in the most recent release, `2023.11.22`. Thus, I'd urge to merge this PR and create a new release that really is compatible with 3.7 and 3.8 (as defined in [`setup.py`](https://github.com/TUDelft-CNS-ATM/bluesky/blob/2023.11.22/setup.py#L57-L58)).
> Restore Python <3.9 compatibility

- bluesky/resources/graphics/bluesky.qss
- bluesky/ui/qtgl/mainwindow.py
When running bluesky from another directory but the source dir, the style sheet cannot resolve the path to icon files and just displays some text on buttons (see image below).
This PR makes use of bluesky's resource path resolver to add an entry to the search path for resource files.
> set search path for Qt resources in style sheet

- bluesky/pathfinder.py
When providing the workdir command line argument, the current implementation fails with the following error:
```
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/home/stanley/Documents/s-aman/code/atc_gym/lib/bluesky_simulator/BlueSky.py", line 9, in <module>
sys.exit(main())
^^^^^^
File "/home/stanley/Documents/s-aman/code/atc_gym/lib/bluesky_simulator/bluesky/__main__.py", line 35, in main
bs.init(**args)
File "/home/stanley/Documents/s-aman/code/atc_gym/lib/bluesky_simulator/bluesky/__init__.py", line 71, in init
pathfinder.init(workdir)
File "/home/stanley/Documents/s-aman/code/atc_gym/lib/bluesky_simulator/bluesky/pathfinder.py", line 140, in init
for subdir in map(workdir.joinpath, …
```
> fix type of workdir in pathfinder

- bluesky/__init__.py
- bluesky/network/server.py
When starting BlueSky with the `--workdir` argument, it is not passed to the simulation nodes. Therefore, it is impossible to, for instance, load plugins from the working directory. Furthermore, while the server creates plugin, scenario, cache, and output inside the working directory, the nodes operate on the "~/bluesky" directory. 
This PR might only work after #577 has been merged. Otherwise the `--workdir` argument is not working as expected.
> set workdir for nodes when starting via Server object

- bluesky/simulation/screenio.py
- bluesky/ui/qtgl/gltraffic.py
Hello,
Currently, it is not possible to unselect a route after asking for it. The sim nodes will keep sending the route until a reset is given.  This allows a client to deselect a route by calling `POS` again. So it effectively just toggles the route.
It should be possible to close issue #360 with this fix.
Andres
> add ability to unselect routes

- bluesky/traffic/performance/openap/perfoap.py
Hello,
There is an issue where all fixing aircraft get the performance values of a `B744`. 
In line 76 of `perfoap.py` there is a check to convert to a known aircraft type. Even if a valid aircraft type is created, like an `A320`, the check will fail because the `self.coeff.actypes_fixwing` list has the `A320` listed as `a320`.
Here is the output of `self.coeff.actypes_fixwing`
```bash
['a19n', 'a20n', 'a21n', 'a318', 'a319', 'a320', 'a321', 'a332', 'a333', 'a343', 'a359', 'a388', 'b37m', 'b38m', 'b39m', 'b3xm', 'b734', 'b737', 'b738', 'b739', 'b744', 'b748', 'b752', 'b763', 'b772', 'b773', 'b77w', 'b788', 'b789', 'c550', 'crj9', 'e145', 'e170', 'e190', 'e195', 'e75l', 'glf6', 'a124', 'a306', 'a310', 'at72', 'at75', 'at76', 'b733', 'b735', 'b762', 'b77l', 'c25a', 'c525', 'c56x', 'crj2', …
```
> Stop fixwing aircraft from always being a 744
