TUDelft-CNS-ATM/bluesky

bluesky/sim/pygame/simulation.py
bluesky/stack/stack.py
bluesky/tools/aero.py
bluesky/traf/metric.py
bluesky/ui/pygame/screen.py

simt in pygame
wgs84 type in aero
metrics module fix

simt, aero wgs84, metrics fix

---

bluesky/stack/synthetic.py

Most important changes:
- synthetics module now correctly uses traffic.create function
- added two new synthetics modes (row and column) both allow a conflict to be created of a row or column of AC flying at specified angle towards each other. 
Column function:
Row function:

fixed, improved and expanded synthetics module

---

bluesky/settings.py
bluesky/traf/perf.py
bluesky/traf/perfbada.py

For https://github.com/ProfHoekstra/bluesky/issues/69

verbose info on missing flight's aircraft performance model

---

bluesky/tools/ctools/geo.hpp

Some of the geo code was a little bit too obscure, so I added some references to the used formulas.

added few references and comments

---

bluesky/traffic/asas/StateBasedCD.py

Fixed overestimation of distances & bug in looping through conflist_all (conflicts were removed while looping through the list).

Fixed ASAS distance and ResumeNav loop

---

Makefile
bluesky/navdatabase/navdatabase.py
bluesky/test/__init__.py
bluesky/test/tcp/conftest.py
bluesky/test/tcp/test_simple.py
bluesky/test/traffic/__init__.py
bluesky/test/traffic/conftest.py
bluesky/test/traffic/test_route_wpt.py
bluesky/test/traffic/test_traffic.py
bluesky/test/traffic/test_trafficarrays.py
bluesky/tools/trafficarrays.py
bluesky/traffic/route.py
bluesky/traffic/traffic.py

This pull request mainly fixes some identified bugs plus some modest reorganisation.
Joost et al: if you could verify using your scenario testing, that would be much appreciated.
I have produced unit tests for the refactored and some other code based on my understanding of what the code should do.
Tests pass:
`================================================= 22 passed in 10.29 seconds =================================================`

Bug.fixes, mainly on route.py

---

Makefile
bluesky/stack/stack.py
bluesky/test/traffic/__init__.py
bluesky/test/traffic/conftest.py
bluesky/test/traffic/test_route_wpt.py
bluesky/test/traffic/test_traffic.py
bluesky/test/traffic/test_trafficarrays.py
bluesky/tools/aero.py
bluesky/traffic/performance/legacy/perfbs.py

- Mainly comments on tests.
- Apparent bugs in HELP (showhelp) code in `stack.py`
- Also simple helper functions for converting distance and speed.
Thanks :)

Doc.tweaks

---

plugins/opensky.py

An option for limiting traffic to your own receiver(s)

Add opensky_ownonly option

---

.gitignore
MANIFEST.in
__main__.py
requirements.txt
setup.py

BlueSky can now be installed by:
```
python setup.py install
```
To be installable with `pip`, just upload to PyPI with twine (requires a developer account - I'd be happy to register the package, but leave it to the BlueSky team to decide):
```
python setup.py sdist bdist_wheel
twine upload dist/*
```

Created bluesky Python package

---

bluesky/simulation/pygame/simulation.py
bluesky/simulation/qtgl/simulation.py
bluesky/stack/stack.py

Stack method `checkfile()` was renamed to `checkscen()` in 7d49e948 but calls to this method in simulation.py were not updated.

Bugfix renamed checkfile() to checkscen()

---

bluesky/traffic/asas/MVP.py

As discussed in our meeting, I have created a pull request to update the MVP resolution calculations. The calculations now follow Hoekstra's equations and the correct resolution maneuvers are initiated.

MVP resolution calculations

---

bluesky/tools/datalog.py

Add write() function
Add fname property
Add possibility to add a prefix (backwards compatible)

Add features to datalog

---

docs/python_demo.ipynb

I fixed a small issue with the python interface demo jupyter notebook. The example can now be properly run without any changes to the code of the BlueSky package.

fixed issue with python interface demo

---

BlueSky.py

There should be a helpful --help command line option for BlueSky, so that you don't have to search the wiki or the source code to figure out which options are available.

Added --help command to explain command line options.

---

bluesky/traffic/autopilot.py

self.reached was initialised instead of self.idxreached

Fix small typo in Autopilot.

---

bluesky/traffic/autopilot.py

index missing to self.alt in line 565

Small error to autopilot.py

---

bluesky/traffic/autopilot.py

Index to ap.alt added on line 510

Small fix to altitude update in autopilot.py

---

bluesky/traffic/autopilot.py
bluesky/ui/loadvisuals_txt.py
bluesky/ui/qtgl/aman.py
bluesky/ui/qtgl/console.py
bluesky/ui/qtgl/customevents.py
bluesky/ui/qtgl/docwindow.py
bluesky/ui/qtgl/glhelpers.py
bluesky/ui/qtgl/glnavdata.py
bluesky/ui/qtgl/glpoly.py
bluesky/ui/qtgl/gltraffic.py
bluesky/ui/qtgl/gui.py
bluesky/ui/qtgl/guiclient.py
bluesky/ui/qtgl/infowindow.py
bluesky/ui/qtgl/mainwindow.py
bluesky/ui/qtgl/nd.py
bluesky/ui/qtgl/radarwidget.py
bluesky/ui/qtgl/settingswindow.py
bluesky/ui/qtgl/tiledtexture.py
check.py
data/html/Installation.html
extra/blipdriver/blipdriver.py
extra/blipdriver/glhelpers.py
extra/textclient/textclient.py
requirements.txt
setup-python.bat
utils/gltest.py

Here is an attempt at migrating to pyqt6. I get several dialog box warnings when using it

A (semi) working version of pyqt6

---

BlueSky.py
bluesky/ui/console/consoleui.py
bluesky/ui/qtgl/glhelpers.py
bluesky/ui/qtgl/infowindow.py

pyqt6: I don't think there are any other major changes so that bluesky works for both pyqt6 and pyqt5.
textual: I added some buttons in the batch view to switch active nodes. I think most of the functionality that a console client would need is there. It just needs some cleaning up. 
An extra feature that would be nice is to include completed/pending scenarios in the table rather than just the active scenarios. I think that would require some small changes in ```server.py``` so that it keeps this information when running batches and then sends it to a console client if one is connected.

pyqt6 plus textual updates

---

bluesky/ui/console/consoleui.py

Moved the node switching tree to the bottom right.
Next thing should be to make update rates from ```screenio.py``` dynamic.

move node tree to bottom

---

bluesky/core/simtime.py
bluesky/core/varexplorer.py
bluesky/network/client.py
bluesky/network/node.py
bluesky/network/node_mt.py
bluesky/network/server.py
bluesky/test/__init__.py
bluesky/tools/datalog.py
bluesky/tools/misc.py
bluesky/traffic/performance/bada/coeff_bada.py
bluesky/traffic/trafficgroups.py
bluesky/ui/qtgl/gltraffic.py
bluesky/ui/qtgl/mainwindow.py
check.py
plugins/metrics.py

Having some fun with my new python book so I decided to find places to unpack in a nice way.
[Line 148](https://github.com/amorfinv/bluesky/blob/3e4be485eb989964735af08d7262bf86978c557f/bluesky/network/server.py#L148) of ```server.py``` changes like this,
```python
route, eventname, data = msg[:-2], msg[-2], msg[-1]
*route, eventname, data = msg
```
Similarly, [line 152](https://github.com/amorfinv/bluesky/blob/3e4be485eb989964735af08d7262bf86978c557f/bluesky/network/client.py#L152) of ```client.py```,
```python
route, eventname, data = msg[:-2], msg[-2], msg[-1]
self.sender_id = route[0]
route.reverse()
self.sender_id, *_, eventname, data = msg
```
I got rid of ```route.reverse()``` since it isn't used downstream or referenced anywhere else inside the ```receive()``` method. However, I …

Sleeker unpacking plus f-strings

---

plugins/geofence.py

Noticed a small bug when using geofence plugin after performing a ```reset```.
-Andres

bug in geofence plugin

---

bluesky/traffic/route.py

Can be merged. numpy => math because of numpy changes in newest versions

Route numpy

---

bluesky/ui/qtgl/mainwindow.py

Separate isdark() function for Windows

Dark and Light mode for Windows

---

bluesky/network/npcodec.py

This will fix the following execution error:
ValueError: The binary mode of fromstring is removed, use frombuffer instead

Use np.frombuffer instead of np.fromstring

---

bluesky/traffic/performance/openap/coeff.py
bluesky/traffic/performance/openap/perfoap.py
pyproject.toml

Reads coefficients directly from the openap module instead of from local files. Adds openap as a dependency.

openap integration

---

bluesky/traffic/autopilot.py

Hello,
Per the response to issue #590, I am making a PR to update the `DEST` command to allow speed constraints and have a default of no speed constraint.
-Andres

Make dest command accept speed constraints
